### ISSUE TITLE
Windows build issues

### ISSUE THREAD

**Issue by fritzmg** [cyberspectrum/pharpiler#2]
As mentioned on the Contao forum, when trying to build the Contao Manager `.phar` under Windows (with `./vendor/bin/pharpiler.bat compile`) the following error occurs:
```
$ ./vendor/bin/pharpiler.bat compile

Warning: proc_open(): CreateProcess failed, error code - 267 in C:\Users\Spooky\Documents\VCS\contao-manager\vendor\symfony\process\Process.php on line 310


  [Symfony\Component\Process\Exception\RuntimeException]
  Unable to launch a new process.


compile [<file>] [<composer>]
```
This can happen when a relative path is passed to `proc_open` instead of an absolute path, or if the path does not exist.

The latter seems to be the case. As far as I have debugged, `PackageInformation::loadVersionInformationFromGit` will be executed (at least) twice during build. During the first run, `$this->getPackageDirectory()` returns `"C:\Users\Spooky\Documents\VCS\contao-manager"` for example. During the second run (which is where `new Process` will fail) that function returns `"C:\Users\Spooky\Documents\VCS\contao-manager/vendor/php"`. _This path does not exist!_

**Comment by discordier** [comment]
Could you test again using the latest commit in the hotfix branch?

**Comment by fritzmg** [comment]
Yep, that seems to work!

Now I get another error when building `contao-manager`:
```
$ ./vendor/bin/pharpiler.bat compile


  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "C:/Users/Spooky/Documents/GitHub/contao-manager/app/console cache:clear --env=phar --no-debug --no-war
  mup" failed.
  Exit Code: 1(General error)
  Working directory: C:\Users\Spooky\Documents\GitHub\contao-manager
  Output:
  ================
  Error Output:
  ================
  'C:/Users/Spooky/Documents/GitHub/contao-manager/app/console' is not recognized as an internal or external command,
  operable program or batch file.


compile [<file>] [<composer>]
```
But that's another story entirely :). (And you predicted that [here](https://community.contao.org/de/showthread.php?65512-Composer-Nutzung-vereinfachen&p=431220&viewfull=1#post431220))

**Comment by discordier** [comment]
Ok, I'll close this one here then.
